blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/nathsudi/utility/tree/main/docs
    about: Check out the documentation for usage guides and examples
  - name: 💬 Discussions
    url: https://github.com/nathsudi/utility/discussions
    about: Ask questions and discuss ideas with the community
