name: Auto-assign PR

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add size labels
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: 10
          s_label: 'size/s'
          s_max_size: 50
          m_label: 'size/m'
          m_max_size: 200
          l_label: 'size/l'
          l_max_size: 500
          xl_label: 'size/xl'
        continue-on-error: true
